### PR TITLE
Add VS code config to .gitignore

### PR DESCRIPTION
**Pull request by ggravlingen**
#### Reason for change
In https://github.com/Arelle/Arelle/pull/223#discussion_r919513692 it was suggested to not support all IDE-flavors. I still use the containerised environment propoed in that PR. Everytime I start up the Arelle-environment , I have to checkout my VS-code branch and start from there. Adding these lines to the .gitignore-file would allow me to have the VS code config present at all times without having to stash it or switch branches.

#### Description of change
I have added two lines to ignore the two folders created by VS code.

#### Steps to Test

**review**:
@Arelle/arelle

### CODE REVIEW

**Comment by ggravlingen** [comment]
@austinmatherne-wk would you consider this to allow the use of VS code without having to commit anything to this project?

**Comment by aviary-wf** [comment]
## Security Insights
No security relevant content was detected by automated scans.

## Action Items
* Review PR for [security impact](https://wiki.atl.workiva.net/display/SECURITY/Development+Security+Review+Guidelines); comment "security review required" if needed or unsure
* Verify [`aviary.yaml`](https://wiki.atl.workiva.net/pages/viewpage.action?pageId=42762752#SecurityInsightFramework&Tooling-ConfiguringAviary) coverage of security relevant code
---
_Questions or Comments? Reach out on Slack: #support-infosec._

**Review by austinmatherne-wk — APPROVED** [review]
> @austinmatherne-wk would you consider this to allow the use of VS code without having to commit anything to this project?

Absolutely! I was actually planning on doing this myself 🙂

**Comment by ggravlingen** [comment]
Great, thanks!

**Pull request merged**
